const test = require('node:test'); const assert = require('node:assert/strict');
const core = require('../miniprogram/utils/core'); const dates = require('../miniprogram/utils/date');
function record(extra) { return Object.assign({ type: 'expense', id: core.id('bill'), categoryId: 'food', amountCents: 1000, refundCents: 0, date: '2024-02-10', time: '12:00', payment: '微信', note: '午饭', createdAt: 1, updatedAt: 1 }, extra); }
function state(records) { const s = core.freshState(); s.records = records || []; return s; }
test('金额按分计算，0.1 + 0.2 精确为 0.30', () => { assert.equal(core.amountToCents('0.1') + core.amountToCents('0.2'), 30); assert.equal(core.money(30), '0.30'); assert.equal(core.amountToCents('9999999.99'), 999999999); });
test('拒绝零消费、负数、过多小数、非数字和溢出金额', () => { for (const n of ['0','-1','1.234','abc','NaN','1e3','10000000']) assert.throws(() => core.amountToCents(n)); assert.equal(core.amountToCents('0', true), 0); });
test('闰年二月和普通年份二月范围正确', () => { assert.deepEqual(dates.range('month','2024-02-10'), { start: '2024-02-01', end: '2024-02-29' }); assert.equal(dates.range('month','2025-02-10').end, '2025-02-28'); assert.throws(() => dates.parseDate('2025-02-29')); });
test('周从周一开始且支持跨年', () => { assert.deepEqual(dates.range('week','2025-01-01'), { start: '2024-12-30', end: '2025-01-05' }); assert.equal(dates.dayCount('2024-12-30','2025-01-05'), 7); });
test('31 日切换到二月不会跳到三月', () => { assert.equal(dates.shiftPeriod('month','2024-01-31',1), '2024-02-01'); assert.equal(dates.shiftPeriod('year','2024-02-29',1),'2025-01-01'); });
test('筛选同时满足日期、分类、支付方式及关键词，并按时间降序', () => { const s = state([record({ id:'a' }), record({ id:'b', time:'13:00', note:'咖啡' }), record({ id:'c', categoryId:'shopping', payment:'现金' }), record({ id:'d', date:'2024-03-01', note:'咖啡' })]); assert.deepEqual(core.filterRecords(s,{ start:'2024-02-01',end:'2024-02-29',categoryId:'food',payment:'微信',query:'咖啡' }).map(r=>r.id), ['b']); assert.equal(core.filterRecords(s)[0].id,'d'); });
test('退款扣回原消费日期，分组小计与统计一致', () => { const s = state([record({ amountCents: 1000, refundCents: 200 }),record({ amountCents:300 })]); assert.equal(core.total(s.records),1100); const stat = core.statistics(s,'month','2024-02-10','2024-03-10'); assert.equal(stat.totalText,'11.00'); assert.equal(stat.refundText,'2.00'); assert.equal(stat.categories[0].amountText,'11.00'); assert.equal(core.groups(s,core.filterRecords(s))[0].expenseText,'11.00'); assert.equal(stat.bars[9].cents,1100); });
test('全额退款记录仍可从明细查看，净消费为零', () => { const s = state([record({ refundCents:1000 })]); const stat = core.statistics(s,'day','2024-02-10','2024-02-10'); assert.equal(stat.count,1); assert.equal(stat.totalText,'0.00'); assert.equal(stat.categories.length,0); });
test('当期日均使用已过自然日；历史周期使用完整天数', () => { const s = state([record({ date:'2024-02-01',amountCents:2900 })]); const current = core.statistics(s,'month','2024-02-10','2024-02-10'); assert.equal(current.days,10); assert.equal(current.averageText,'2.90'); assert.equal(core.statistics(s,'month','2024-02-10','2024-03-01').averageText,'1.00'); });
test('年度按月聚合，包含闰年的全部消费', () => { const s = state([record({ date:'2024-02-29',amountCents:500 }),record({date:'2024-12-31',amountCents:700})]); const stat = core.statistics(s,'year','2024-02-01','2025-01-01'); assert.equal(stat.days,366); assert.equal(stat.bars.length,12); assert.equal(stat.bars[1].cents,500); assert.equal(stat.bars[11].cents,700); });
test('空账本有稳定的零金额、分类和趋势数据', () => { const stat = core.statistics(state(),'week','2024-02-10','2024-02-10'); assert.equal(stat.totalText,'0.00'); assert.equal(stat.peakText,'0.00'); assert.equal(stat.bars.length,7); assert.equal(stat.categories.length,0); });
test('新增及修改记录保留身份，非法退款及未来日期被拒绝', () => { const s = state(); const input = { type:'expense', amount:'12.34',categoryId:'food',date:'2024-02-10',time:'12:34',payment:'微信',note:' 午饭 ',refund:'2.34' }; const r = core.createRecord(s,input); assert.equal(core.net(r),1000); assert.equal(r.note,'午饭'); const changed = core.createRecord(s,Object.assign({},input,{amount:'15.00'}),r); assert.equal(changed.id,r.id); assert.equal(changed.createdAt,r.createdAt); assert.throws(()=>core.createRecord(s,Object.assign({},input,{refund:'20'}))); assert.throws(()=>core.createRecord(s,Object.assign({},input,{date:dates.shiftDays(dates.dateKey(new Date()),1)}))); });
test('备份拒绝重复 ID、未知分类、小数分值及畸形日期', () => { const good = state([record({id:'a'})]); core.validateState(good); for (const mutate of [s=>s.records.push({...s.records[0]}),s=>s.records[0].categoryId='missing',s=>s.records[0].amountCents=1.2,s=>s.records[0].date='2024-02-30',s=>s.records[0].refundCents=2000,s=>s.categories.push({...s.categories[0]})]) { const s = JSON.parse(JSON.stringify(good)); mutate(s); assert.throws(()=>core.validateState(s)); } });
test('CSV 包含 UTF-8 BOM，转义逗号引号换行，防止备注公式执行', () => { const s = state([record({ note:'=SUM(1,2)"\n备注' })]); const csv = core.csv(s); assert.equal(csv.charCodeAt(0),0xfeff); assert.ok(csv.includes('"\'=SUM(1,2)""\n备注"')); assert.ok(csv.includes('有效金额（元）')); });
test('分页或最近记录的日期小计仍包含当天完整筛选结果',()=>{ const records=[record({id:'a',amountCents:200}),record({id:'b',amountCents:300})]; const s=state(records); const grouped=core.groups(s,records.slice(0,1),records); assert.equal(grouped[0].records.length,1); assert.equal(grouped[0].expenseText,'5.00'); });
