const test = require('node:test'); const assert = require('node:assert/strict'); const store = require('../miniprogram/utils/store'); const core = require('../miniprogram/utils/core');
const input = { type:'expense', amount:'20.00', categoryId:'food', date:'2024-02-10', time:'12:00', payment:'微信', note:'午饭', refund:'0' };
let data; let failKey;
function clone(v) { return v === undefined ? '' : JSON.parse(JSON.stringify(v)); }
test.beforeEach(()=>{ data = new Map(); failKey = ''; global.wx = { getStorageSync: key=>clone(data.get(key)), setStorageSync: (key,value)=>{ if (key === failKey) throw new Error('full'); data.set(key,clone(value)); } }; });
test('初始化为空账本，增改删记录后重新读取保持一致',()=>{ assert.equal(store.read().records.length,0); const r = store.saveRecord(input); assert.equal(store.read().records.length,1); store.saveRecord({...input,amount:'35.00'},r.id); assert.equal(store.read().records[0].amountCents,3500); store.removeRecord(r.id); assert.equal(store.read().records.length,0); });
test('写入失败不会覆盖上一次成功保存的数据',()=>{ const r = store.saveRecord(input); failKey = store.KEY; assert.throws(()=>store.saveRecord({...input,amount:'88.00'},r.id),/保存失败/); assert.equal(store.read().records[0].amountCents,2000); });
test('损坏的本地数据不会被当作空账本覆盖',()=>{ data.set(store.KEY,{corrupted:true}); assert.throws(()=>store.read(),/原数据未被覆盖/); assert.deepEqual(data.get(store.KEY),{corrupted:true}); });
test('删除分类迁移全部历史账单，并保留金额与退款',()=>{ store.saveRecord({...input,refund:'3'}); store.removeCategory('food','other'); const s = store.read(); assert.ok(!s.categories.some(c=>c.id==='food')); assert.equal(s.records[0].categoryId,'other'); assert.equal(core.total(s.records),1700); });
test('分类重命名即时反映到历史账单，拒绝同名分类',()=>{ store.saveRecord(input); store.saveCategory('吃饭','🍜','food','expense'); assert.equal(core.decorate(store.read(),store.read().records[0]).categoryName,'吃饭'); assert.throws(()=>store.saveCategory('购物','🛒','food','expense')); });
test('备份往返完整保留账单、分类和预算',()=>{ store.saveRecord(input); store.setBudget('1234.56'); const state = store.parseBackup(store.backupText()); assert.equal(state.settings.budgetCents,123456); assert.equal(state.records.length,1); assert.equal(state.categories.length,22); });
test('恢复前保留副本，导入失败保持原账本，副本可恢复',()=>{ store.saveRecord(input); const replacement = core.freshState(); store.restore(replacement); assert.equal(store.read().records.length,0); store.restoreSafety(); assert.equal(store.read().records.length,1); failKey = store.KEY; assert.throws(()=>store.restore(replacement)); assert.equal(store.read().records.length,1); });
test('无法保存恢复前副本时不修改当前数据',()=>{ store.saveRecord(input); failKey = store.SAFETY_KEY; assert.throws(()=>store.restore(core.freshState()),/已取消恢复/); assert.equal(store.read().records.length,1); });
test('拒绝错误来源及格式备份，且不改变现有账本',()=>{ store.saveRecord(input); for (const raw of ['not-json','{}',JSON.stringify({app:'daily-expense-miniapp',version:1,state:{}})]) assert.throws(()=>store.parseBackup(raw)); assert.equal(store.read().records.length,1); });
test('可从有效备份恢复损坏账本，保留原始损坏副本',()=>{ data.set(store.KEY,{corrupted:true}); store.restore(core.freshState()); assert.equal(store.read().records.length,0); assert.deepEqual(data.get(store.SAFETY_KEY),{corrupted:true}); });
test('月预算支持关闭；修改不存在的账单不会新增记录',()=>{ store.setBudget('2000'); assert.equal(store.read().settings.budgetCents,200000); store.setBudget('0'); assert.equal(store.read().settings.budgetCents,0); assert.throws(()=>store.saveRecord(input,'missing')); assert.equal(store.read().records.length,0); });
